---
- name: "Tests"
  hosts: client
  tasks:
    - name: Test availability slave
      uri:
        url: "http://{{ ansible_host }}"
        method: GET
        return_content: true
      register: this
      failed_when: "'Student Checking App' not in this.content"
...
